### ISSUE TITLE
[Bug] tinycolor2 missing as a dependency

### ISSUE THREAD

**Issue by joeyballentine** [anubra266/pill-pity#5]
When installing Pill-Pity via npm, it is missing the dependency `tinycolor2`.

**Comment by anubra266** [comment]
The issue arose because `tinycolor2` has been replaced with `@ctrl/tinycolor` to get better tree-shaking in chakra UI. So it's been updated here as of [v0.2.3](https://github.com/anubra266/pill-pity/releases/tag/v0.2.3)
